---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-site-operator-kube-stager-io-v1-stagingsite
  failurePolicy: Fail
  name: mstagingsite.kb.io
  rules:
  - apiGroups:
    - site.operator.kube-stager.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - stagingsites
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-job-operator-kube-stager-io-v1-backup-advanced
  failurePolicy: Fail
  name: backup-handler.operator.kube-stager.io
  rules:
  - apiGroups:
    - job.operator.kube-stager.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backups
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-site-operator-kube-stager-io-v1-stagingsite-advanced
  failurePolicy: Fail
  name: stagingsite-handler.operator.kube-stager.io
  rules:
  - apiGroups:
    - site.operator.kube-stager.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - stagingsites
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-config-operator-kube-stager-io-v1-mongoconfig-deletion
  failurePolicy: Fail
  name: mongoconfig-delete-handler.operator.kube-stager.io
  rules:
  - apiGroups:
    - config.operator.kube-stager.io
    apiVersions:
    - v1
    operations:
    - DELETE
    resources:
    - mongoconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-config-operator-kube-stager-io-v1-mysqlconfig-deletion
  failurePolicy: Fail
  name: mysqlconfig-delete-handler.operator.kube-stager.io
  rules:
  - apiGroups:
    - config.operator.kube-stager.io
    apiVersions:
    - v1
    operations:
    - DELETE
    resources:
    - mysqlconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-config-operator-kube-stager-io-v1-redisconfig-deletion
  failurePolicy: Fail
  name: redisconfig-delete-handler.operator.kube-stager.io
  rules:
  - apiGroups:
    - config.operator.kube-stager.io
    apiVersions:
    - v1
    operations:
    - DELETE
    resources:
    - redisconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-config-operator-kube-stager-io-v1-serviceconfig-deletion
  failurePolicy: Fail
  name: serviceconfig-delete-handler.operator.kube-stager.io
  rules:
  - apiGroups:
    - config.operator.kube-stager.io
    apiVersions:
    - v1
    operations:
    - DELETE
    resources:
    - serviceconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-config-operator-kube-stager-io-v1-serviceconfig
  failurePolicy: Fail
  name: serviceconfig-handler.operator.kube-stager.io
  rules:
  - apiGroups:
    - config.operator.kube-stager.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - serviceconfigs
  sideEffects: None
