# permissions for end users to view mongoconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mongoconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-stager
    app.kubernetes.io/part-of: kube-stager
    app.kubernetes.io/managed-by: kustomize
  name: mongoconfig-viewer-role
rules:
- apiGroups:
  - config.operator.kube-stager.io
  resources:
  - mongoconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.operator.kube-stager.io
  resources:
  - mongoconfigs/status
  verbs:
  - get
