# permissions for end users to view importexportdata.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: importexportdata-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-stager
    app.kubernetes.io/part-of: kube-stager
    app.kubernetes.io/managed-by: kustomize
  name: importexportdata-viewer-role
rules:
- apiGroups:
  - importer.operator.kube-stager.io
  resources:
  - importexportdata
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - importer.operator.kube-stager.io
  resources:
  - importexportdata/status
  verbs:
  - get
